apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: your-database-name
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  PGDATA: /var/lib/postgresql/data/pgdata