kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv2-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/postgresql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv2-claim
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi